### ISSUE TITLE
Proposal for change in the Translate by Method API

### ISSUE THREAD

**Issue by Rafagd** [grantshandy/libretranslate-rs#1]
I saw your project a couple of days ago in Reddit, and I couldn't help but notice you had a bunch of hardcoded methods for translating to and from a series of languages. 

What do you think about the changes I've made in my fork of the project?
https://github.com/Rafagd/libretranslate-rs

**Comment by grantshandy** [comment]
Absolutely! This looks perfect!

I'm going to open a pull request and merge it right now.
