### ISSUE TITLE
Error in API call

### ISSUE THREAD

**Issue by ToferC** [grantshandy/libretranslate-rs#6]
Hi Grant - first of all - great work on the crate. I had set it up and was using it in testing in an Actix-Web app and it was working well, but a few days ago it stopped working with the following error:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Unable to find translatedText in parsed JSON")', src/main.rs:172:101```

I'm thinking there might have been a change in the LibreTranslate API

Here's the test snippet that mirrors my app:

```rust
use libretranslate::{translate, Language};

#[tokio::main]
async fn main() {
    let mut translate_strings: Vec<String> = Vec::new();

    let nodes = vec![
        ("father", "person"),
        ("manager", "role"),
        ("gen x", "person"),
    ];
    
    for n in &nodes {
        translate_strings.push(format!("{}.\n", &n.0));
    };

    let source = Language::English;
    let target = Language::French;

    let input = translate_strings.concat();

    let data = translate(source, target, input)
        .await
        .unwrap();

    let mut phrases: Vec<(String, String)> = Vec::new();

    //let en = data.input.split(". ").into_iter();
    let fr = data.output.split(".\n");
    let en = data.input.split(".\n");

    for (f, e) in fr.zip(en) {
        if e != "" {
            phrases.push((e.to_lowercase().replace("/", ""), f.to_lowercase().replace("/","")));
        };
    };

    println!("{:?}", &phrases);
```

**Comment by PJ-Finlay** [comment]
https://github.com/uav4geo/LibreTranslate/issues/82

@pierotofy

**Comment by PJ-Finlay** [comment]
It may make sense to point the default rust bindings to one of the [mirrors](https://github.com/uav4geo/LibreTranslate/issues/78) instead of libretranslate.com to take pressure off the main site.

**Comment by pierotofy** [comment]
Yeah ideally any bindings library should allow developers to choose a host to point to (and to not default to libretranslate.com).

We'd love to be able to provide a public API translation for everyone, but it's just not sustainable.

You can still use the API endpoints from libretranslate.com, but now you need an API key for programmatic access.

**Comment by ToferC** [comment]
Makes perfect sense, @pierotofy. I'd suggest the requirement should be documented in the crate and a clearer error message be transmitted back.

**Comment by grantshandy** [comment]
Hey thanks for all this, I'll make the changes now.

**Comment by grantshandy** [comment]
Hey thanks for the issue, I should have solved the problem.

You can now [translate using a custom URL](https://docs.rs/libretranslate/0.3.0/libretranslate/fn.translate_url.html), as well as get [better errors from the website](https://github.com/grantshandy/libretranslate-rs/blob/e787e466c1189b3312e32d63f584ae4ffede31ad/src/lib.rs#L204-L207).

See the [example](https://github.com/grantshandy/libretranslate-rs/blob/main/examples/custom_url.rs).

Does this fix your problem? @ToferC, @pierotofy & @PJ-Finlay

**Comment by grantshandy** [comment]
Does this fix your problem? @ToferC

**Comment by ToferC** [comment]
Thanks @grantshandy - fixes look great.
