### ISSUE TITLE
Compatibility unic-langid

### ISSUE THREAD

**Issue by kellpossible** [grantshandy/libretranslate-rs#7]
It would be nice to have some inbuilt or optional compatibility with https://crates.io/crates/unic-langid/0.9.0 which is used by a lot of localization/language related crates in the Rust ecosystem.

**Comment by grantshandy** [comment]
Thanks! I'll definitely do this :)

**Comment by grantshandy** [comment]
Done :)

Done: https://docs.rs/libretranslate/0.4.1/libretranslate/languages/enum.Language.html#method.from_unic_langid
